# pipeline.py
"""
The conductor. This file answers ONE question: "in what order does the
cleaning happen?" -- read the step lists below top to bottom.

Every step is  step(df, ctx) -> df  (see models.RunContext). Steps decorated
@value_only (see guards.py) are additionally checked so they can never turn a
populated value into a blank. To add a cleaning step, write the function in
the right steps/ module and add one line to a list here.

This pipeline has no AI dependency: no model is loaded and no column is
generated by anything other than deterministic rules.
"""

import os
import time

import pandas as pd

from config import SHOW_STEP_PROGRESS
from .audit import log_step, new_log
from .loaders import load_file, describe_source
from .masks import build_disguised_mask, build_flag_masks, empty_mask, flag_app_duplicates, flag_app_invalid
from .models import CleanResult, RESERVED_COLUMNS, RunContext
from .output.report import build_dataset_report
from .textutil import normalize_name

from .steps.columns import (
    flag_problem_columns,
    standardize_column_names, dedupe_column_names, flag_unnamed_columns,
    resolve_duplicate_columns, detect_duplicate_content_columns,
)
from .steps.structure import (
    find_blank_columns,
    remove_repeated_header_rows, remove_total_rows,
    drop_duplicate_rows, dedupe_by_app_number, drop_blank_rows_and_columns,
)
from .steps.values import (
    trim_whitespace, fix_encoding_issues, format_phone_numbers,
    summarize_missing_values,
    standardize_casing, apply_category_mapping,
)
from .steps.dates import convert_dates
from .steps.dtypes import infer_and_fix_dtypes


STRUCTURE_STEPS = [
    # -- columns
    flag_problem_columns,
    standardize_column_names,
    dedupe_column_names,
    # -- detect fully blank columns ONCE, so every per-cell step below can
    #    skip them. Must run AFTER the column names are final.
    find_blank_columns,
    flag_unnamed_columns,
    # -- junk rows
    remove_repeated_header_rows,
    remove_total_rows,
    # -- values (all @value_only)
    trim_whitespace,
    fix_encoding_issues,
    format_phone_numbers,
    # convert_disguised_blanks,   # COMMENTED OUT: placeholders (N/A, TBD ...) are kept and flagged PURPLE
    #                             # instead of removed -- see steps/values.py and masks.build_disguised_mask
    summarize_missing_values,
    standardize_casing,
    apply_category_mapping,
    # -- duplicates and blanks
    resolve_duplicate_columns,
    drop_duplicate_rows,
    dedupe_by_app_number,
    drop_blank_rows_and_columns,
]

TYPE_STEPS = [
    convert_dates,
    infer_and_fix_dtypes,
]

FINAL_STEPS = [
    detect_duplicate_content_columns,
]

# Stages that aren't individual step(df, ctx) functions (mask-building,
# report assembly) but still take real time on a large/messy file, and so
# still get a number in the progress count below.
EXTRA_STAGE_LABELS = [
    "build_flag_masks",
    "flag_app_duplicates_and_invalid",
    "build_disguised_mask",
    "build_report",
]

TOTAL_STAGES = len(STRUCTURE_STEPS) + len(TYPE_STEPS) + len(FINAL_STEPS) + len(EXTRA_STAGE_LABELS)


def _progress_start(stage_num, label):
    """
    Prints "  [ 4/23]  17%  trim_whitespace..." with NO trailing newline, so
    the step name is visible on screen the whole time that step is running
    (that's the point -- on a big/messy file some steps take a while, and
    without this the terminal just looks frozen). _progress_done() finishes
    the same line once the step actually returns.
    """
    if not SHOW_STEP_PROGRESS:
        return
    pct = int(round(100 * stage_num / TOTAL_STAGES))
    print(f"  [{stage_num:>2}/{TOTAL_STAGES}] {pct:>3}%  {label}...", end="", flush=True)


def _progress_done(elapsed):
    if not SHOW_STEP_PROGRESS:
        return
    print(f" done ({elapsed:.2f}s)")


def _record_comparison(original_df, df, ctx):
    """Logs + stores the original-vs-final comparison the report prints."""
    stats, log = ctx.stats, ctx.log

    original_dtypes = {normalize_name(c): str(original_df[c].dtype) for c in original_df.columns}

    rows_diff = df.shape[0] - original_df.shape[0]
    cols_diff = df.shape[1] - original_df.shape[1]
    original_cols = set(original_dtypes.keys())
    final_cols = set(df.columns)
    cols_added = sorted(final_cols - original_cols)
    cols_removed = sorted(original_cols - final_cols)
    stats["cols_added"] = cols_added
    stats["cols_removed"] = cols_removed

    dtype_changes = []
    for col in df.columns:
        if col in original_dtypes and original_dtypes[col] != str(df[col].dtype):
            dtype_changes.append((col, original_dtypes[col], str(df[col].dtype)))
    stats["dtype_changes"] = dtype_changes

    log_step(log, "compare_original_to_final",
             f"original: {original_df.shape[0]} rows / {original_df.shape[1]} cols | "
             f"final: {df.shape[0]} rows / {df.shape[1]} cols | "
             f"row change: {rows_diff:+d}, column change: {cols_diff:+d} | "
             f"columns added: {cols_added if cols_added else 'none'} | "
             f"columns removed: {cols_removed if cols_removed else 'none'}")


def _attach_source_file(mask):
    """
    Add the source_file=False column to an issue mask in ONE operation.

    Why not `mask["source_file"] = False`:
      every mask is built column-by-column in masks.py, and each
      `mask[col] = ...` splits off a fresh internal block. By the time we
      get here each mask is "highly fragmented" (that is exactly what
      pandas' PerformanceWarning says). Adding a brand-new column to a
      fragmented frame is an insert, and that is what triggers the warning.
      pd.concat builds a single, de-fragmented frame in one go instead --
      same result, no warning, no per-column bookkeeping.
    """
    if "source_file" in mask.columns:
        return mask
    extra = pd.DataFrame(False, index=mask.index, columns=["source_file"])
    return pd.concat([mask, extra], axis=1)


def _preserve_reserved_name_clashes(df, ctx):
    """
    If the source file already has a column that NORMALIZES to a reserved
    name ("source_file", "missing_count" -- see models.RESERVED_COLUMNS),
    rename it before the pipeline adds its own generated column of that
    name, so the file's real data is never silently overwritten.

    BUG FIX: this protection existed in the pre-modular pipeline (renaming
    to "<name>_original") but was lost in the rewrite -- the generated
    df["source_file"] = ... assignment below used to clobber a genuine
    "Source File" / "SOURCE_FILE" / "source_file" data column with no
    rename, no log entry and no warning.
    """
    for reserved in RESERVED_COLUMNS:
        clashes = [c for c in df.columns if normalize_name(c) == reserved]
        if not clashes:
            continue
        for col in clashes:
            new_name = f"{reserved}_original"
            while new_name in df.columns:
                new_name += "_"
            df = df.rename(columns={col: new_name})
            log_step(ctx.log, "preserve_existing_reserved_column",
                     f"input column '{col}' normalizes to reserved name '{reserved}' -- "
                     f"renamed to '{new_name}' so it is not overwritten by the "
                     f"pipeline's generated '{reserved}' column")
    return df


def clean_file(path):
    """Cleans one file and returns a CleanResult. Raises on unreadable files."""
    start_time = time.time()

    loaded = load_file(path)
    original_df = loaded.original_df
    df = original_df.copy()

    ctx = RunContext(
        source_name=os.path.basename(path),
        log=new_log(path),
        stats=describe_source(loaded),
        number_display=loaded.number_display,
    )
    log_step(ctx.log, "find_header_row",
             f"header found at row {loaded.header_row} ({loaded.header_row} junk row(s) skipped above it)")

    stage = 0

    for step in STRUCTURE_STEPS:
        stage += 1
        _progress_start(stage, step.__name__)
        step_start = time.time()
        df = step(df, ctx)
        _progress_done(time.time() - step_start)
        if step is dedupe_column_names:
            # Column names are now standardized + de-duplicated, so this is
            # the earliest point a clash with a reserved name is final --
            # catch it before any later step treats the real column as
            # the pipeline's own reserved one.
            df = _preserve_reserved_name_clashes(df, ctx)

    ctx.fail_mask = empty_mask(df)
    for step in TYPE_STEPS:
        stage += 1
        _progress_start(stage, step.__name__)
        step_start = time.time()
        df = step(df, ctx)
        _progress_done(time.time() - step_start)

    for step in FINAL_STEPS:
        stage += 1
        _progress_start(stage, step.__name__)
        step_start = time.time()
        df = step(df, ctx)
        _progress_done(time.time() - step_start)

    stage += 1
    _progress_start(stage, EXTRA_STAGE_LABELS[0])
    step_start = time.time()
    missing_mask, price_review_mask, price_cols_checked = build_flag_masks(
        df, ctx.log, blank_cols=ctx.blank_cols
    )
    _progress_done(time.time() - step_start)

    stage += 1
    _progress_start(stage, EXTRA_STAGE_LABELS[1])
    step_start = time.time()
    app_duplicate_mask, id_cols_checked = flag_app_duplicates(df, empty_mask(df), ctx.log)
    missing_mask, app_invalid_mask, _ = flag_app_invalid(df, missing_mask, empty_mask(df), ctx.log)
    review_mask = price_review_mask | app_duplicate_mask | app_invalid_mask
    _progress_done(time.time() - step_start)

    # The APP column is excluded here: its blanks/placeholders already have
    # their own dedicated sheet (ID Anomalies) and its own colour, so they
    # should not also show up on the Disguised Blanks (PURPLE) sheet.
    stage += 1
    _progress_start(stage, EXTRA_STAGE_LABELS[2])
    step_start = time.time()
    disguised_mask, disguised_by_column = build_disguised_mask(
        df, ctx.log, exclude_cols=id_cols_checked, blank_cols=ctx.blank_cols
    )
    _progress_done(time.time() - step_start)

    stage += 1
    _progress_start(stage, EXTRA_STAGE_LABELS[3])
    step_start = time.time()

    # Generated field: source_file.  It contains only the name of the input
    # file being cleaned and is deliberately added after all cleaning/detection
    # so it cannot affect the cleaner's decisions.
    df["source_file"] = ctx.source_name

    # Keep every issue mask aligned with the final dataframe.
    #
    # BUG FIX: this used to be a `for mask_name in (...)` loop reading
    # `locals()[mask_name]`. That worked for the masks that happen to be
    # local variables, but `fail_mask` lives on ctx (ctx.fail_mask), not as
    # a local -- so the loop raised KeyError: 'fail_mask' at the very end of
    # every single clean_file() call, after all the real cleaning had already
    # run. That is why every file reported "Failed: <name> -- 'fail_mask'".
    #
    # Each assignment has to be written back explicitly: pd.concat returns a
    # NEW frame, it does not mutate the mask in place.
    missing_mask = _attach_source_file(missing_mask)
    ctx.fail_mask = _attach_source_file(ctx.fail_mask)
    review_mask = _attach_source_file(review_mask)
    price_review_mask = _attach_source_file(price_review_mask)
    app_duplicate_mask = _attach_source_file(app_duplicate_mask)
    app_invalid_mask = _attach_source_file(app_invalid_mask)
    disguised_mask = _attach_source_file(disguised_mask)

    _record_comparison(original_df, df, ctx)

    stats = ctx.stats
    stats["raw_missing_cells"] = int(df.isna().sum().sum())
    stats["missing_cells_highlighted"] = int(missing_mask.sum().sum())
    stats["failed_parse_cells_highlighted"] = int(ctx.fail_mask.sum().sum())
    stats["review_cells_highlighted"] = int(review_mask.sum().sum())
    stats["price_anomaly_cells_highlighted"] = int(price_review_mask.sum().sum())
    stats["app_duplicate_cells_highlighted"] = int(app_duplicate_mask.sum().sum())
    stats["app_invalid_cells_highlighted"] = int(app_invalid_mask.sum().sum())
    stats["disguised_blanks_flagged"] = int(disguised_mask.sum().sum())
    stats["disguised_blank_columns"] = disguised_by_column
    stats["duplicate_content_columns_flagged"] = len(ctx.duplicate_name_map)
    stats["price_columns_checked"] = price_cols_checked
    stats["id_columns_checked"] = id_cols_checked
    stats["blank_columns_skipped"] = len(ctx.blank_cols)

    stats["processing_seconds"] = round(time.time() - start_time, 2)

    summary = build_dataset_report(original_df, df, stats, ctx.log)
    _progress_done(time.time() - step_start)

    return CleanResult(
        df=df,
        original_df=original_df,
        log=ctx.log,
        summary=summary,
        date_cols=ctx.date_cols,
        missing_mask=missing_mask,
        fail_mask=ctx.fail_mask,
        review_mask=review_mask,
        price_review_mask=price_review_mask,
        app_duplicate_mask=app_duplicate_mask,
        app_invalid_mask=app_invalid_mask,
        duplicate_name_map=ctx.duplicate_name_map,
        money_cols=ctx.money_cols,
        number_display=ctx.number_display,
        blue_header_cols=ctx.blue_header_cols,
        blue_header_notes=ctx.blue_header_notes,
        disguised_mask=disguised_mask,
    )